#!/usr/bin/env python3
import sys
import shutil
import subprocess


def main():
    # Check if an action is provided
    if len(sys.argv) < 1:
        print(f"Error: No action provided. Arguments: {sys.argv}")
        sys.exit(0)
    # Check if the action is valid
    action = sys.argv[1]
    if action in ('remove', 'purge'):
        dir_path = '/usr/share/ethercat_igh_dkms'
        # Attempt to remove the directory if it's empty
        try:
            print(f"Try to remove directory: {dir_path}")
            shutil.rmtree(dir_path)
        except OSError:
            # Directory not empty or cannot be removed
            pass
        except Exception as e:
            print(f"Error: {cmd} failed.")
            sys.exit(1)


if __name__ == '__main__':
    main()
